# Generated by Django 5.2.1 on 2025-05-27 10:03

import accounts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invite',
            options={},
        ),
        migrations.AlterField(
            model_name='group',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default=accounts.models.generate_invite_code, max_length=32, unique=True),
        ),
    ]
