# Generated by Django 4.2.23 on 2025-06-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_friendship_options_groupmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="invite_uses_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times the current invite code has been used",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="max_invite_uses",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Maximum times the current invite code can be used before rotation",
            ),
        ),
    ]
