# Generated by Django 5.2.1 on 2025-05-27 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_friendship_options_groupmember'),
        ('files', '0002_alter_file_upload_alter_version_upload_fileshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_as_a', to='graph.node')),
                ('node_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_as_b', to='graph.node')),
            ],
            options={
                'unique_together': {('node_a', 'node_b'), ('node_b', 'node_a')},
            },
        ),
        migrations.CreateModel(
            name='NodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_nodes', to='files.file')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_files', to='graph.node')),
            ],
            options={
                'unique_together': {('node', 'file')},
            },
        ),
        migrations.CreateModel(
            name='NodeShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('permission', models.CharField(choices=[('R', 'Read'), ('W', 'Write')], default='R', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='graph.node')),
                ('shared_with_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_nodes', to='accounts.group')),
                ('shared_with_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('node', 'shared_with_group'), ('node', 'shared_with_user')},
            },
        ),
    ]
