version: "3.8"

services:
  # ─── MySQL Database ─────────────────────────────────────────────────────────
  vault_db:
    image: mysql:8.0
    container_name: vault_db
    restart: always
    environment:
      MYSQL_DATABASE: vault_db
      MYSQL_USER: vault_user
      MYSQL_PASSWORD: s3cr3tpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # ─── Django Backend ────────────────────────────────────────────────────────
  vault_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vault_backend
    depends_on:
      - vault_db
    env_file:
      - ./backend/.env
    environment:
      MYSQL_HOST: vault_db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: vault_db
      MYSQL_USER: vault_user
      MYSQL_PASSWORD: s3cr3tpass
      # Add DJANGO_SECRET_KEY and any other required vars in backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code

  # ─── Vite Frontend ─────────────────────────────────────────────────────────
  vault_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vault_frontend
    depends_on:
      - vault_backend
    environment:
      # Tell Vite where to find GraphQL (inside Docker Compose)
      VITE_GRAPHQL_URL: http://vault_backend:8000/graphql/
      # For reliable file watching in Docker
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      # Prevent host from overwriting node_modules inside container
      - /app/node_modules

volumes:
  db_data:
