# Generated by Django 4.2.23 on 2025-06-11 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_friendship_options_groupmember"),
        ("graph", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="channel",
            unique_together={("node",), ("direct_user1", "direct_user2")},
        ),
        migrations.AddField(
            model_name="channel",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_channel",
                to="accounts.group",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("DIRECT", "Direct"),
                    ("NODE", "Node-linked"),
                    ("GROUP", "Group"),
                    ("PUBLIC", "Public"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="channel",
            unique_together={("node",), ("direct_user1", "direct_user2"), ("group",)},
        ),
    ]
