# Generated by Django 5.2.1 on 2025-05-26 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(max_length=500, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='version',
            name='upload',
            field=models.FileField(max_length=500, upload_to='uploads/%Y/%m/%d/versions/'),
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('permission', models.CharField(choices=[('R', 'Read'), ('W', 'Write')], default='R', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='files.file')),
                ('shared_with_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to='accounts.group')),
                ('shared_with_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('file', 'shared_with_group'), ('file', 'shared_with_user')},
            },
        ),
    ]
